import Head from "next/head";
import MainCard from "@/components/MainCard";
import { motion } from "framer-motion";
import { Data } from "use-lanyard";
import Card from "@/components/Card";

export default function NotFound({ user }: { user: Data }) {
  return (
    <>
      <Head>
        <title>gus.sh - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.div
        key="maindiv"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.2, ease: "easeInOut" }}
        className="relative mx-auto grid max-w-3xl grid-cols-12 gap-6 px-6 pb-40"
      >
        <MainCard user={user} />
        <Card className="group col-span-12 h-44 md:col-span-2">
          <div className="lights flex w-full animate-pulse select-none flex-col items-center justify-center text-5xl md:text-2xl">
            <span>🚧👷🚧</span>
          </div>
        </Card>
        <Card className="group col-span-12 h-44 text-pink-200 text-glow-violet-500">
          <h1 className="lights center w-full select-none self-center text-center font-mono text-3xl font-bold text-black dark:text-white">
            under construction
          </h1>
        </Card>
      </motion.div>
    </>
  );
}
